### PR TITLE
update spreadsheet cc

### PR DESCRIPTION
**Pull request by choper725**

### CODE REVIEW

**Comment by oblomov-dev** [comment]
thanks

**Comment by choper725** [comment]
ohh yes you are right, ill try to check what an be done on cc load

**Comment by choper725** [comment]
should now behave as expected with #1101

**Comment by oblomov-dev** [comment]
Nice! works now on my end 👏
image

**Comment by choper725** [comment]
i can try create a check module avaliable method as a custom cc, and we can probebly implement it in the xml view, to catch all of the non cc ciontrols who are not in openui5…
could be a better way tho..

for now can figure a way without try define the module with a try catch.

the part on whete and how to implement the check logic is the intresting one…

ill do something, we cam echance it from there,
let me know if you think of a better idea @oblomov-dev

**Pull request merged**
