### PR TITLE
update chartjs CC

### PR DESCRIPTION
**Pull request by choper725**

### CODE REVIEW

**Comment by choper725** [comment]
hi @oblomov-dev 

thx for the tip, made it to work,
but now i get a new abap error updating the model,

image


i updated demo 148 with this error

**Comment by oblomov-dev** [comment]
Thank you I will check this.

**Comment by choper725** [comment]
> Thank you I will check this.

found a bug in the new model update fix you made, (you said expect bugs :) ),
before a model update the binded model and the object (chartjs object model) is the same

after a model update it seems that not all values are getting copied to the model
image

at first before model update everything is fine..

still trying to understand what causes this..

**Comment by oblomov-dev** [comment]
to the first problem, i can see the error but don't know what the initial problem is. I am wondering about the following:
plugins is type string_table and it is empty with the first request:
image

but at the forntend, values are filled:
image

How are you doing this? ;)

i think the problem is then just a follow up error because, the binding method wants to write a table with multiple colums to a string table this creates the error here:
image

i iwll check the second error after fixing the first one, maybe they correspond to each other.

**Comment by choper725** [comment]
haha yes you are right, the plugins is an object insert via the CC render based on the js libraries you want to load in the load_js method.
but i think im having problems (the second problem), even when there are no plugins choosen.

ill create a demo for it without plugins.
the pictures from abap debugger are from that demo, ill just PR it.

**Comment by oblomov-dev** [comment]
(1)
ok then i think it is not the problem with the binding. just try to delete the attributes again before the backend request, otherwise you will map a table with multiple rows into a string_table (plugins) and this can not work.

(2)
yes a demo just with the specific issue would be nice.

**Comment by choper725** [comment]
updated demo 148 with the problem,
the abap debugger pictures from above are relevant

**Comment by oblomov-dev** [comment]
lets continue here https://github.com/abap2UI5/abap2UI5/issues/782

**Pull request merged**
