### PR TITLE
short http get method

### PR DESCRIPTION
**Pull request by oblomov-dev**

### CODE REVIEW

**Comment by choper725** [comment]
hi oblomov, alot od f this break with this

**Comment by oblomov-dev** [comment]
Mhh I thought i just deleted the code which was commented anyway or did I miss something?

**Comment by choper725** [comment]
not sure about all of it but im pretty sure lines 381-385 are the part we handle sending object to t_arg

**Comment by choper725** [comment]
last i changed there was in #1116 not sure who else commented it out.. was away from this project for a bit..

**Comment by choper725** [comment]
oh no my bad, i looked at the wrong thing!!

**Comment by oblomov-dev** [comment]
yes i think i only deleted commented lines, will merge it now, but if something goes wrong, just let me know and we can undo changes. thank you for having an eye on it!

**Pull request merged**
