### PR TITLE
font awsome free icons support

### PR DESCRIPTION
**Pull request by choper725**
will make a guide how the resources should be handled..

### CODE REVIEW

**Comment by oblomov-dev** [comment]
cool 😎 thanks!

**Comment by choper725** [comment]
it got also the js animation option and full support for pro version.

needs to tweak the metadata file in order for it to work but for the free version now its fully compatible, with the jadeliver resources i created from github

**Comment by oblomov-dev** [comment]
yes good work and great idea 👍

image

**Comment by oblomov-dev** [comment]
@choper725  fyi reassigned the font class to package 01

**Pull request merged**
