### PR TITLE
Added URLHelper Methods

### PR DESCRIPTION
**Pull request by cwildt**
Added URLHelper Methods redirect, triggerEmail, triggerSms and triggerTel

### CODE REVIEW

**Comment by oblomov-dev** [comment]
nice, thank you!

Do you happen to have a code snippet so I can see how to use it?

**Comment by cwildt** [comment]
`    view->button(
        text  = `Trigger Email`
        press = client->_event_client(
            val   = client->cs_event-urlhelper
            t_arg = VALUE #(
                ( `TRIGGER_EMAIL` )
                ( `{ "email": "john.smith@sap.com", "subject": "Test Email", "body": "testbody", "cc": false, "bcc": false }` ) ) ) ).`

**Comment by cwildt** [comment]
```
    view->button(
        text  = `Redirect`
        press = client->_event_client( val   = client->cs_event-urlhelper
                                       t_arg = VALUE #( ( `REDIRECT` )
                                                        ( `{ "url": "http://www.sap.com", "newWindow": true }`) ) ) ).
```

**Comment by cwildt** [comment]
```
    view->button( text  = `Trigger Telephone`
                  press = client->_event_client( val   = client->cs_event-urlhelper
                                                 t_arg = VALUE #( ( `TRIGGER_TEL` )
                                                                  ( `{ "tel": "+49 6227 747474" }` ) ) ) ).
```

**Pull request merged**
