### PR TITLE
text element on new popup classes + range tokens

### PR DESCRIPTION
**Pull request by choper725**
+ xml additions

### CODE REVIEW

**Comment by choper725** [comment]
so long to cross check…

**Comment by oblomov-dev** [comment]
The Cross Check is not important for merging, you have to update the branch, I made updates in between

**Comment by choper725** [comment]
> The Cross Check is not important for merging, you have to update the branch, I made updates in between

still takes hours.. is it a problem ?

**Comment by oblomov-dev** [comment]
No it's no problem, but did you see my comment concerning the text elements you created for the range values? I am not sure if it's a good idea merging this. I think selects will not work when you change the value of LE, GE etc

**Comment by choper725** [comment]
> No it's no problem, but did you see my comment concerning the text elements you created for the range values? I am not sure if it's a good idea merging this. I think selects will not work when you change the value of LE, GE etc

the value is not text-element only the names.. will this cause a problem ??

**Comment by oblomov-dev** [comment]
yes this are both constants, token values mapped to range values. for example LE in a range table is the same as <={LOW} as a token and vice versa. you can not change this otherwise the range tables are not valid anymore. recommend to add an extra description field to the output if you want to change the output for the user.

**Comment by choper725** [comment]
ok ill remove the text elements, maybe will do that locally

**Pull request closed without merging**
